internal:
  api:
    server_protocol: ${INTERNAL_SERVER_PROTOCOL:http}
    server_address: ${INTERNAL_API_SERVER_URL:localhost}
    server_port: ${INTERNAL_API_SERVER_PORT:8080}
    key: ${INTERNAL_API_KEY:local-api-key}
    key_header_name: ${INTERNAL_API_HEADER_NAME:Internal-API-Key}
    url:
      sse_notify: ${INTERNAL_API_URL_SSE_NOTIFY:/ap1/v1/sse/notify}