version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/server
hooks:
  ApplicationStop:
    - location: application-stop.sh
  AfterInstall:
    - location: after-install.sh
  ApplicationStart:
    - location: application-start.sh