server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  profiles:
    include: value
  datasource:
    hikari:
      jdbc-url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
      pool-name: Spring-HikariPool
      max-lifetime: 60000
      maximum-pool-size: 30
    userlock:
      jdbc-url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
      pool-name: UserLock-HikariPool
      max-lifetime: 60000
      maximum-pool-size: 20
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQLDialect
        order_updates: true
        order_inserts: true
        jdbc:
          batch_size: 100
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  messages:
    basename: message.web, message.achievement, message.user
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: 6379
  cloud:
    aws:
      credentials:
        access-key: ${AWS_CREDENTIAL_ACCESS_KEY}
        secret-key: ${AWS_CREDENTIAL_SECRET_KEY}
      sqs:
        endpoint: ${AWS_SQS_ENDPOINT}
        region: ${AWS_SQS_REGION}
logging:
  level:
    root: info