spring:
  datasource:
    batch:
      jdbc-url: ${BATCH_DATASOURCE_URL}
      username: ${BATCH_DATASOURCE_USERNAME}
      password: ${BATCH_DATASOURCE_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
      pool-name: metadata-pool
    hikari:
      jdbc-url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
      pool-name: hikari-pool
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never
  profiles:
    include: value
  cloud:
    aws:
      credentials:
        access-key: ${AWS_CREDENTIAL_ACCESS_KEY}
        secret-key: ${AWS_CREDENTIAL_SECRET_KEY}
      sqs:
        endpoint: ${AWS_SQS_ENDPOINT}
        region: ${AWS_SQS_REGION}
elastic:
  username: ${ELASTIC_USERNAME}
  password: ${ELASTIC_PASSWORD}
  host: ${ELASTIC_HOST}
  port: ${ELASTIC_PORT}
  truststore:
    location: ${ELASTIC_TRUSTSTORE_LOCATION}
    password: ${ELASTIC_TRUSTSTORE_PASSWORD:}
server:
  port: 9080