quest:
  page:
    size: 20

notification:
  page:
    size: 10

security:
  url:
    allowed_url: ["/", "/css/**", "/js/**", "/image/**", "/error", "/api/v1/auth/**"]
    admin_url: ["/admin/**"]
    logout_url: "/api/v1/auth/logout"
    internal_url: ["/api/v1/sse/notify"]
  origin:
    allowed_origin: ["http://localhost:9090", "https://dailyquest.mooo.com", "http://localhost:9080"]
  key:
    internal_api_key: ${INTERNAL_API_KEY:local-api-key}

spring:
  jwt:
    secret: ${JWT_SECRET}

google:
  client-id: ${GOOGLE_CLIENT_ID}

redis:
  key:
    exp_table: ${REDIS_EXP_TABLE_KEY}
    nickname_prefix: ${REDIS_NICKNAME_PREFIX_KEY}
    nickname_postfix: ${REDIS_NICKNAME_POSTFIX_KEY}
    settings: ${REDIS_SETTINGS_KEY}
    quest_clear_exp: ${REDIS_QUEST_CLEAR_EXP_KEY}
    quest_clear_gold: ${REDIS_QUEST_CLEAR_GOLD_KEY}
    max_reward_count: ${REDIS_MAX_REWARD_COUNT_KEY}

elastic:
  username: ${ELASTIC_USERNAME}
  password: ${ELASTIC_PASSWORD}
  host: ${ELASTIC_HOST}
  port: ${ELASTIC_PORT}
  truststore:
    location: ${ELASTIC_TRUSTSTORE_LOCATION}
    password: ${ELASTIC_TRUSTSTORE_PASSWORD:}

jwt:
  access_token_validation_millisecond_string: ${ACCESS_TOKEN_VALIDATION_MILLISECOND}
  refresh_token_validation_millisecond_string: ${REFRESH_TOKEN_VALIDATION_MILLISECOND}
  access_token_name: ${ACCESS_TOKEN_NAME}
  refresh_token_name: ${REFRESH_TOKEN_NAME}
  use_secure: ${TOKEN_USE_SECURE:true}
  same_site: ${TOKEN_SAME_SITE_STRATEGY:strict}
  domain: ${TOKEN_DOMAIN}

api:
  batch:
    server-protocol: ${BATCH_SERVER_PROTOCOL:http}
    server-address: ${BATCH_API_SERVER_URL:localhost}
    server-port: ${BATCH_API_SERVER_PORT:9080}
    key: ${BATCH_API_KEY:local-api-key}
    key-header-name: ${BATCH_API_HEADER_NAME:Batch-API-Key}
    url:
      check-and-achieve: ${BATCH_API_URL_CHECK_AND_ACHIEVE:/api/v1/check-and-achieve}
